version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
            - deploy:
                filters:
                    branches: 
                        only:
                            - master
                name: private-server
                command: ssh -o "StrictHostKeyChecking no" $SSH_DETAILS "cd ~/bot; git pull; npm install; forever stopall; forever start index.js"

