version: 2
jobs:
    build-test-v10:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run:
                name: Install depndencies
                command: npm install
            - run:
                name: Linter
                command: npm run lint
            - run:
                name: Security Audit
                command: npm audit
            - run:
                name: Test
                command: npm test
            - run:
                name: Code coverage
                command: npm run coverage
    build-test-v8:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - run:
                name: Install depndencies
                command: npm install
            - run:
                name: Linter
                command: npm run lint
            - run:
                name: Security Audit
                command: npm audit
            - run:
                name: Test
                command: npm test
            - run:
                name: Code coverage
                command: npm run coverage
        
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-test-v8
            - build-test-v10
